local_repository(
    name = "pycross_image",
    path = "../..",
)

# -----------------------------------------

load("@pycross_image//bazel:repositories.bzl", "repositories")

repositories()

# -----------------------------------------

load(
    "@pycross_image//bazel:workspace0.bzl",
    "setup_aspect_bazel_lib",
    "setup_bazel_gazelle",
    "setup_bazel_skylib",
    "setup_rules_go",
    "setup_rules_oci",
    "setup_rules_python",
    "setup_zig_toolchains",
)

setup_zig_toolchains()

setup_rules_go()

setup_bazel_gazelle()

setup_bazel_skylib()

setup_rules_python()

setup_aspect_bazel_lib()

setup_rules_oci()

# -----------------------------------------

load(
    "@pycross_image//bazel:workspace1.bzl",
    "setup_oci_containers",
    "setup_rules_pycross",
)

setup_rules_pycross()

setup_oci_containers()

# -----------------------------------------

load(
    "@rules_pycross//pycross:workspace.bzl",
    "lock_repo_model_pdm",
    "pycross_lock_repo",
)
load(
    "@pycross_toolchains//:defs.bzl",
    "environments",
)

pycross_lock_repo(
    name = "pypi",
    lock_model = lock_repo_model_pdm(
        lock_file = "@//:pdm.lock",
        project_file = "@//:pyproject.toml",
    ),
    package_build_dependencies = {
        "grpclib": [
            "setuptools",
            "wheel",
        ],
    },
    target_environments = environments,
)

# -----------------------------------------

load(
    "@pypi//:defs.bzl",
    "install_deps",
)

install_deps()
